language: python
python:
    - "3.7"

os:
    - linux

dist: xenial

sudo: true

install:
    - sudo apt-get update
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python setup.py install

script:
    - pytest --doctest-modules

after_success:
    - coveralls
